<div id="login_wrapper">
	<div id="login_content">
		<h2>CNY-SiteManager</h2>
		<h3>Forgot Password</h3>

		<form method="post" action="">
		<p>
			<label class="label required" for="username">Username:</label>
			<input id="username" type="text" value="" name="username"/>
		</p>

		<input class="submit" type="submit" value="Send">
		<div style="clear: both;padding-top:30px;"></div>
		<center style="color:#ff0000;font-weight:bold"><?php echo @$this->error ?></center>
		</form>
	</div>
	<div style="clear: both;"></div>
</div>