<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>A Table</title>
		<link type="text/css" rel="stylesheet" href="/css/reset-fonts-grids.css"/>
		<link type="text/css" href="/css/jquery-ui-1.8.14.custom.css" rel="stylesheet" />	
		<link rel="stylesheet" type="text/css" href="/css/superfish.css" media="screen">
		<style type="text/css" media="all">
			@import "/css/jtip.css";
		</style>
		<link type="text/css" rel="stylesheet" href="/css/wf-styles.css"/>
<!--[if IE 6]>
<link type="text/css" rel="stylesheet" href="/css/wf-ie6.css"/>
<![endif]-->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.js"></script>
		<script type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
		<script type="text/javascript" src="/js/hoverIntent.js"></script>
		<script type="text/javascript" src="/js/superfish.js"></script>
		<script type="text/javascript">

		// initialise plugins
		jQuery(function(){
			jQuery('ul.sf-menu').superfish();
		});

		</script>
		<script src="/js/jtip.js" type="text/javascript"></script>
		<script type="text/javascript" src="/js/jquery.cycle.all.latest.js"></script>
<!--[if IE]>
.rounded-corners {
  behavior: url(border-radius.htc);
}
<![endif]-->
	<script type="text/javascript" src="/js/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
	<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
	<link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" /> 
	<script type="text/javascript">
		$(document).ready(function() { 

			$(".option-page-link").fancybox();
 
		});
	</script>
		<script type="text/javascript">
			var jTipTimeout;			//Stores the setTimeout for the delayed tooltip.
			var jTipTimeDelay = 1000;
			natDays = [];
			function nationalDays(date) {
			for (i = 0; i < natDays.length; i++) {
                        if (date.getMonth() == natDays[i][0] - 1
                        && date.getDate() == natDays[i][1]) {
                                return [false, natDays[i][2] + '_day'];
                        }
                }
                return [true, ''];
        }

        function noWeekendsOrHolidays(date) {
                var noWeekend = $.datepicker.noWeekends(date);
                if (noWeekend[0]) {
                        return nationalDays(date);
                } else {
                        return noWeekend;
                }
        }


        $(function() {
                $("#datepicker").datepicker({
			showOn: "button",
			buttonImage: "/images/calendar.gif",
			buttonImageOnly: true,
                        minDate: +2,
						maxDate: "+14D",
                        hideIfNoPrevNext: true,
                        beforeShowDay: $.datepicker.noWeekends,
                        altField: '#alternate',
                });
        });

$(document).ready(function() {
    $('.slideshow').cycle({
		fx: 'fade' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
	});
});
		</script>
	</head>
	<body > 
				<div id="page-content"  >
		 			<?=$this->layout()->content?>
				</div>
			</div>
			
	</body>
</html>
