<head>
    <link type="text/css" rel="stylesheet" href="/Tooltip/Tooltip.css" />
    <script type="text/javascript" src="/Tooltip/Tooltip.js"></script> 
    
<script language="javascript">
$(document).ready(function(){
    $('.calc').change(function(){
        var total = 0;
        $('.calc').each(function(){
            if($(this).val() != '')
            {
                total += parseInt($(this).val());
            }
        });
        $('#total').html(total);
    });
})(jQuery);

</script>
</head>
<form id="userForm" method="post" action="" enctype="multipart/form-data">
    
<h2>Edit Dish</h2>
<ul class="navigation">
    <li><input type="submit" value="Save"/></li>
    <li><a class="btn_back" href="/admin/dishes">Back</a></li>
    <!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>


<input type="hidden" name="id" value="<?=$this->dish['id']?>"/>
<div class="datatable">
	<table id="mediamanagertable">
		<thead>
                        <tr class="header">
				<th width="175" class="first">Dish# <?=$this->dish['id']?></th>
				<th width="575"><b><?=$this->dish['name']?></b></th>
				<th class="lastrow"></th>
			</tr>			
		</thead>
		<tfoot>
			<tr class="footer">
				<td colspan="4">&nbsp;</td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>
                                    <span class="tooltip" onmouseover="tooltip.pop(this, 'The dish name will appear on the front end website (www.atablenyc.com). Our customers will be selecting items based on, amongst others, the name of a dish. The name should not be more than .. characters.')">
                                        Name :
                                    </span>
                                </td>
				<td>
					<input type="text" name="data[name]" size="62" value="<?=$this->dish['name']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
                                <td>
                                    <span class="tooltip" onmouseover="tooltip.pop(this, 'The name of the chef will be used to keep track of who developed this dish.')">
                                        Chef :
                                    </span>
                                </td>
				<td>
                                        <?=$this->formSelect('data[chef_category_id]', $this->dish['chef_category_id'], array('id'=>'chef_category_id', 'style'=>'width:190px;', 'class'=>'form-field'), $this->chef_categories)?>
				</td>
				<td class="lastrow"></td>
                        </tr>
			<tr>
				<td class="firstrow">Description :</td>
				<td>
					<textarea name="data[description]" rows="5" cols="60"><?=$this->dish['description']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr>
				<td class="firstrow">Dish Category :</td>
				<td>
					<?=$this->formSelect('data[dish_category_id]', $this->dish['dish_category_id'], array('id'=>'dish_category_id', 'style'=>'width:190px;', 'class'=>'form-field'), $this->dish_categories)?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr>
				<td class="firstrow">Food Category :</td>
				<td>
					<?=$this->formSelect('data[food_category_id]', $this->dish['food_category_id'], array('id'=>'food_category_id', 'style'=>'width:190px;', 'class'=>'form-field'), $this->food_categories)?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Season :</td>
				<td>
                                    <?=$this->formSelect('data[season]', $this->dish['season'], array('id'=>'season'), $this->season)?>                                    
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Cuisine Origin :</td>
				<td>
                                    <?=$this->formSelect('data[kitchen_category_id]', $this->dish['kitchen_category_id'], array('id'=>'cuisine', 'style'=>'width:190px;', 'class'=>'form-field'), $this->kitchen_categories)?>                                    
				</td>
				<td class="lastrow"></td>
			</tr>
<!--                        <tr>
				<td class="firstrow">Vegetarian :</td>
				<td>                          
                                    <?php if($this->dish['vegetarian'] == 'yes'){ ?>
                                    <input type="radio" name="data[vegetarian]" value="yes" checked/>Yes
                                    <input type="radio" name="data[vegetarian]" value="no"/>No
                                    <?php }elseif($this->dish['vegetarian'] == 'no'){ ?>
                                    <input type="radio" name="data[vegetarian]" value="yes"/>Yes
                                    <input type="radio" name="data[vegetarian]" value="no" checked/>No
                                    <?php }else{ ?>
                                    <input type="radio" name="data[vegetarian]" value="yes"/>Yes
                                    <input type="radio" name="data[vegetarian]" value="no"/>No
                                    <?php } ?>                                  
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Vegan :</td>
				<td>
                                    <?php if($this->dish['vegan'] == 'yes'){ ?>
                                    <input type="radio" name="data[vegan]" value="yes" checked/>Yes
                                    <input type="radio" name="data[vegan]" value="no"/>No
                                    <?php }elseif($this->dish['vegan'] == 'no'){ ?>
                                    <input type="radio" name="data[vegan]" value="yes"/>Yes
                                    <input type="radio" name="data[vegan]" value="no" checked/>No
                                    <?php }else{ ?>
                                    <input type="radio" name="data[vegan]" value="yes"/>Yes
                                    <input type="radio" name="data[vegan]" value="no"/>No
                                    <?php } ?>
				</td>
				<td class="lastrow"></td>
			</tr>-->
                        <tr>
				<td class="firstrow">To be consumed cold :</td>
				<td>
                                    <?php if($this->dish['cold'] == 'yes'){ ?>
                                    <input type="radio" name="data[cold]" value="yes" checked/>Yes
                                    <input type="radio" name="data[cold]" value="no"/>No
                                    <?php }elseif($this->dish['cold'] == 'no'){ ?>
                                    <input type="radio" name="data[cold]" value="yes"/>Yes
                                    <input type="radio" name="data[cold]" value="no" checked/>No
                                    <?php }else{ ?>
                                    <input type="radio" name="data[cold]" value="yes"/>Yes
                                    <input type="radio" name="data[cold]" value="no"/>No
                                    <?php } ?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Can be frozen :</td>
				<td>
                                    <?php if($this->dish['frozen'] == 'yes'){ ?>
                                    <input type="radio" name="data[frozen]" value="yes" checked/>Yes
                                    <input type="radio" name="data[frozen]" value="no"/>No
                                    <?php }elseif($this->dish['frozen'] == 'no'){ ?>
                                    <input type="radio" name="data[frozen]" value="yes"/>Yes
                                    <input type="radio" name="data[frozen]" value="no" checked/>No
                                    <?php }else{ ?>
                                    <input type="radio" name="data[frozen]" value="yes"/>Yes
                                    <input type="radio" name="data[frozen]" value="no"/>No
                                    <?php } ?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        
                        <tr>
				<td class="firstrow">Cal per serving :</td>
				<td>
                                    <input type="text" name="data[calories]" size="62" value="<?=$this->dish['calories']?>">                                    
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Adult Serving Size (gram) :</td>
				<td>
                                    <input type="text" name="data[serving_size]" size="62" value="<?=$this->dish['serving_size']?>">                                    
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Other nutrition facts:</td>
				<td>
					<input type="text" name="data[nutrition_facts]" size="62" value="<?=$this->dish['nutrition_facts']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Reheating Instructions:</td>
				<td>
					<textarea name="data[reheat_instructions]" rows="5" cols="60"><?=$this->dish['reheat_instructions']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Nutritionist Comment:</td>
				<td>
                                        <textarea name="data[nutritionist_comment]" rows="5" cols="60"><?=$this->dish['nutritionist_comment']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Chef Comment:</td>
				<td>
					<textarea name="data[chef_comment]" rows="5" cols="60"><?=$this->dish['chef_comment']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Wine Pairing:</td>
				<td>
					<textarea name="data[wine_pairing]" rows="5" cols="60"><?=$this->dish['wine_pairing']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="header">
				<th width="125" class="first">Preparation</th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
                        <tr>
				<td class="firstrow"># Servings:</td>
				<td>
					<input type="text" name="data[servings]" size="62" value="<?=$this->dish['servings']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Prep Time (min):</td>
				<td>
					<input type="text" name="data[prep_time]" class="calc" size="62" value="<?=$this->dish['prep_time']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Cooking Time (min):</td>
				<td>
					<input type="text" name="data[cooking_time]" class="calc" size="62" value="<?=$this->dish['cooking_time']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Cooling Time (min):</td>
				<td>
					<input type="text" name="data[cooling_time]" class="calc" size="62" value="<?=$this->dish['cooling_time']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Other Time (min):</td>
				<td>
					<input type="text" name="data[other_time]" class="calc" size="62" value="<?=$this->dish['other_time']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Total Time (min):</td>
				<td>
					<span id="total"><?=$this->dish['total_time']?></span> 
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Appliances needed :</td>
				<td>
<!--                                    <input type="text" name="data[appliance_category_id]" value="<?=$this->dish['appliance_category_id']?>">-->
                                    <?php
                                    $appliance = $this->dish['appliance_category_id'];
                                    $totalNum = count($this->appliance_categories);                                    
                                    $appVal = explode(',', $appliance);                                     
                                    $appNum = count($appVal);
                                    for($i=0; $i<$totalNum; $i++){
                                        if($i < $appNum){                                         
                                        }else{
                                            $appVal[$i] = '';
                                        }}
                                    ?>                                     
                                    <?php foreach($this->appliance_categories as $cart_key => $val) { 
                                            $flag = false;    
                                            for($y=0; $y<$totalNum; $y++){
                                                    if($cart_key == $appVal[$y]){
                                                       $flag=true; 
                                                    }
                                                }   ?>
                                    <?php   if($flag == true){    ?>
                                    <?php   echo $this->formCheckbox('data[appliance_category_id][]', $cart_key, array('checked' => true)) ?> <?=$val; ?>                                    
                                    <?php   }else{?>
                                    <?php   echo $this->formCheckbox('data[appliance_category_id][]', $cart_key, array('checked' => false)) ?> <?=$val;?>
                                    <?php   }} ?>
                                </td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Prep work:</td>
				<td>
                                        <textarea name="data[prep_work]" rows="5" cols="60"><?=$this->dish['prep_work']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Procedures:</td>
				<td>
					<textarea name="data[procedures]" rows="5" cols="60"><?=$this->dish['procedures']?></textarea>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="header">
				<th width="125" class="first">Pricing</th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
                        <tr>
				<td class="firstrow">Sale Price:</td>
				<td>
					$ <input type="text" name="data[price]" value="<?=$this->dish['price']?>">
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>				
                                <td class="firstrow">Price Scale:</td>
				<td>
                                    <?=$this->formSelect('data[price_scale]', $this->dish['price_scale'], array('id'=>'price_scale'), $this->price_scale)?>                                    
				</td>
                                <td class="lastrow"></td>
			</tr>
                        <tr class="header">
				<th width="125" class="first">Allergens</th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
                        <tr>
				<td class="firstrow">Allergens:</td>
				<td>
					<?php
                                            foreach($this->allergenList as $cart_key => $val){
                                                if($val['allergen']){
                                                    echo $val['allergen'].',';
                                                }
                                            }
                                        ?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="header">
				<th width="125" class="first">Other</th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
                        <tr>
				<td class="firstrow">Date first offered:</td>
				<td>
					<input type="text" size="62" name="data[start_date]" class="date-pick" value="<?=$this->dish['start_date']?>" autocomplete="off">
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr>
				<td class="firstrow">Date end offered:</td>
				<td>
                                        <input type="text" size="62" name="data[end_date]" class="date-pick" value="<?=$this->dish['end_date']?>" autocomplete="off">
				</td>
				<td class="lastrow"></td>
			</tr>      
                        <tr>
				<td class="firstrow"># of Weeks on Menu YTD:</td>
				<td>
					<input type="text" name="data[weeks]" value="<?=$this->dish['weeks']?>" DISABLED>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow">Status:</td>
				<td>
					<?=$this->formSelect('data[status]', $this->dish['status'], array('id'=>'status'), $this->statuses)?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr>
				<td class="firstrow"><input type="submit" value="Save"></td>
				<td></td>
				<td class="lastrow"></td>
			</tr>
		</tbody>
	</table>
</div>
<!--<div class="datatable">
    <h2>Allergens</h2>
    <table id="mediamanagertable1">   
        <tr>
            <td class="firstrow">Allergens:</td>
            <td>
                                    <input type="text" name="data[allergen]" value="<?=$this->dish['allergen_category_id']?>">
                <?php
                $allergen = $this->dish['allergen_category_id'];
                $totalNum = count($this->allergen_categories);                                    
                $allVal = explode(',', $allergen);                                     
                $allNum = count($allVal);
                for($i=0; $i<$totalNum; $i++){
                    if($i < $allNum){                                         
                    }else{
                        $allVal[$i] = '';
                    }}
                ?>                                     
                <?php foreach($this->allergen_categories as $cart_key => $val) { 
                        $flag = false;    
                        for($y=0; $y<$totalNum; $y++){
                                if($cart_key == $allVal[$y]){
                                   $flag=true; 
                                }
                            }   ?>
                <?php   if($flag == true){    ?>
                <?php   echo $this->formCheckbox('data[allergen_category_id][]', $cart_key, array('checked' => true)) ?> <?=$val;?>                                    
                <?php   }else{?>
                <?php   echo $this->formCheckbox('data[allergen_category_id][]', $cart_key, array('checked' => false)) ?> <?=$val;?>
                <?php   }} ?>

            </td>
            <td class="lastrow"></td>
        </tr>
        </table>
</div>-->

</form>



    

<div class="datatable">
    <h2>Ingredients</h2>
    <table id="mediamanagertable1">        
        <form id="userForm" method="post" action="/admin/dishes/item-add" enctype="multipart/form-data">
            <input type="hidden" name="dish_id" value="<?=$this->dish['id']?>">            
            <tbody>                
                <?php
                    $id = $this->dish['id'];
                    $tab = 'need';
                    foreach ($this->items[$id] as $item){
                        if (isset($item['ingredient'])) 
                        {                            
                            if ($tab == 'need'){
                ?>  
                <thead>                    
                    <tr class="header">
                        <th class="first">Commodity</th>                        
                        <th>Variety</th>
                        <th>Quantity</th>
                        <th>Unit</th>                        
                        <th>Allergen</th>
                        <th class="last action">Delete</th>
                    </tr>
                </thead>
                <?php 
                    $tab = 'used';
                      } 
                ?>
                    <tr>
                        <td>
                            <?=$item['ingredient']?>  
                        </td>   
                        <td>
                            <?=$item['variety']?>
                        </td>
                        <td>
                            <?=$item['quantity']?>
                        </td>
                        <td>
                            <?=$item['name']?>
                        </td>                        
                        <td>
                            <?=$item['allergen']?>
                        </td>
                        
                        <td class="lastrow"><a href="/admin/dishes/item-delete/dish_id/<?=$id?>/id/<?=$item['id']?>" title="Delete" class="btn_delete" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
                    </tr>
               <?php }
                    }
                    ?>
            </tbody>
            <tfoot>
                <tr class="footer">
                    <thead>
                        <tr class="header">                            
                            <th class="first"><b>Add new Ingredient</b></th>
                            <th><b>Quantity</b></th>
                            <th><b>Unit</b></th>       
                            <th></th>  
                            <th></th>  
                            <th class="last action"></th>                            
                        </tr>
                    </thead>
                    <tr>
                        <td><?=$this->formSelect("ingredient",'', array('id'=>'ingredients_id', 'style'=>'width:190px;', 'class'=>'form-field'), array(""=>"Select Ingredient")+$this->ingredient_categories)?></td>
                        <td><input type="text" name="data[quantity]" size="4" value="<?=$this->quantity?>"></td>                        
                        <td><?=$this->formSelect("unit",'', array('id'=>'units_id'), array(""=>"Select Item")+$this->unit_categories)?></td>
                        <td></td>
                        <td></td>
                        <td><input type="submit" value="Add"></td>
                    </tr>
                </tr>
            </tfoot>
        </form>
    </table>
</div>


<ul class="navigation">
	<li><a class="btn_back" href="/admin/dishes">Back</a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>

<style>
	/* ComboBox special overwrites */
	.ui-button-icon-only .ui-button-text { padding: 0.35em; }
	.ui-autocomplete-input { padding:0 0 0 0.25em; width:150px!important;}
	.ui-autocomplete { text-align: left; height: 200px; overflow: auto; width:250px!important; }
	button.ui-button-icon-only  { height:1.4em; width:2em; top:4px; }
</style>


<script type="text/javascript">
    
$(document).ready(function() {
	$("#chef_category_id").combobox();
        $("#dish_category_id").combobox();
        $("#food_category_id").combobox();
        $("#ingredients_id").combobox();        
        $("#cuisine").combobox();
        $(".date-pick").datepicker();
    });
    
$(document).ready(function() {
	$("#mediamanagertable tbody tr:even").addClass("shadeon");
	$("#mediamanagertable tbody tr:odd").addClass("shadeoff");
        
        $("#mediamanagertable1 tbody tr:even").addClass("shadeon");
	$("#mediamanagertable1 tbody tr:odd").addClass("shadeoff");
        
        $(".date-pick").datepicker();
});

//    $('#ingredients_id').change(function() 
//    {
//        
//        var fileSelect = $("#ingredients_id")[0];
//        var fileName = fileSelect.value;
//        
//        alert(fileName);    
//        fileName = document.forms.ingredient.value;
//        alert(fileName);
//        //call your javascript function here
//    });

</script>