<div class="int-content">
	<h1>My Account</h1>
	<div class="account-wrap">
		<div class="account-nav">
			<ul>
				<li><a href="/wireframe/index/account">Orders</a></li>
				<li><a href="/wireframe/index/accountinfo">My Account Info</a></li>
				<li><a href="/wireframe/index/payment">Payment Information</a></li>
				<li><a href="/wireframe/index/settings">Settings</a></li>
			</ul>
		</div>
		<div class="account-right">
			<div class="checkout-wrap">
				<form action="/wireframe/index/orderconfirm" method="post"> 
					<h2>Order #12340 | 6/30/2011</h2>
					<h2>Delivery Information</h2>
					<div class="row"><label>Name:</label> <span class="fielddata">Dan Testfield</span></div>
					<div class="row"><label>Address 1:</label>  <span class="fielddata">123 Manhattan Street</span></div>
					<div class="row"><label>Address 2:</label>   <span class="fielddata">Apartment 28</span></div>
					<div class="row">
						<div class="city inline-fields">
							<label>City:</label>   <span class="fielddata">New York</span>
							<div class="zip  inline-fields"><label>State:</label> <span class="fielddata">New York</span></div>
							<div class="zip  inline-fields"><label>Zip:</label> <span class="fielddata">10010</span></div>
						</div>
					</div>
					<h2>Contact Information</h2>
					<div class="row"><label>Telephone:</label> <span class="fielddata">212-555-5555</span></div>
					<div class="row"><label>Email:</label> <span class="fielddata">dan@domainname.com</span></div>
					<h2>Payment Information</h2>
					<div class="row"><label>Credit Card:</label> <span class="fielddata">XXXXXXXXXXXXX123</span></div>
					<div class="row">
						<label>Exp Date:</label>
						<div class="cvv  inline-fields"> <span class="fielddata">04/14</span></div>
						<div class="cvv  inline-fields"><label>CVV:</label> <span class="fielddata">123</span></div>
					</div>
					<div class="row"><label>Name:</label> <span class="fielddata">Dan Testfield</span></div>
					<div class="row"><label>Address 1:</label>  <span class="fielddata">123 Manhattan Street</span></div>
					<div class="row"><label>Address 2:</label>   <span class="fielddata">Apartment 28</span></div>
					<div class="row">
						<div class="city inline-fields">
							<label>City:</label>   <span class="fielddata">New York</span>
							<div class="zip  inline-fields"><label>State:</label> <span class="fielddata">New York</span></div>
							<div class="zip  inline-fields"><label>Zip:</label> <span class="fielddata">10010</span></div>
						</div>
					</div>
				</form> 
				<div class="order-sidebar">
					<div class="mid">
						<form action="/wireframe/index/orderconfirm" method="post">
							<h3>Delivery Date: <span class="deliver-date">Wednesday 5/26</span></h3>
							<table class="order-sidebar-table">
								<tr class="order-head">
									<th class="col-item">Item</th>
									<th class="col-qty">Qty</th>
									<th class="col-cost">Cost</th>
								</tr>
								<tr>
									<td valign="top">Sample item Option Title Long Name</td>
									<td valign="top">2</td>
									<td valign="top">$10.00</td>
								</tr>
								<tr>
									<td valign="top">Sample item Option Title Long Name</td>
									<td valign="top">2</td>
									<td valign="top">$10.00</td>
								</tr>
							</table>
							<h3>Delivery Date: <span class="deliver-date">Friday 5/28</span></h3>
							<table class="order-sidebar-table">
								<tr class="order-head">
									<th class="col-item">Item</th>
									<th class="col-qty">Qty</th>
									<th class="col-cost">Cost</th>
								</tr>
								<tr>
									<td valign="top">Sample item Option Title Long Name</td>
									<td valign="top">2</td>
									<td valign="top">$10.00</td>
								</tr>
								<tr>
									<td valign="top">Sample item Option Title Long Name</td>
									<td valign="top">2</td>
									<td valign="top">$10.00</td>
								</tr>
							</table>
							<table class="order-sidebar-table subtotal">
								<tr class="order-head subtotal">
									<th class="col-item">Sub-Total</th>
									<th class="col-qty"></th>
									<th class="col-cost">$38.00</th>
								</tr>
								<tr>
									<td valign="top">Delivery Fee</td>
									<td valign="top"></td>
									<td valign="top">$10.00</td>
								</tr>
								<tr>
									<td valign="top">Tax</td>
									<td valign="top"></td>
									<td valign="top">$3.40</td>
								</tr>
								<tr class="order-head subtotal">
									<th class="col-item">TOTAL</th>
									<th class="col-qty"></th>
									<th class="col-cost">$51.40</th>
								</tr>
							</table>
							<div class="order-submit"><a href="/wireframe/index/order" class="editorder"">< Edit Order</a>
 
						</div> 
					</form>
				</div>
				<div class="bottom"></div> 
		</div>
	</div>			 
			</div>

		</div>

</div>
