<?php $this->layout()->setLayout('account'); ?>
<div class="int-content">
	<div class="account-topnav"><a href="/wireframe/index/account">My Orders</a> | <a href="/wireframe/index/accountinfo" class="active">My Profile</a></div>
	<div class="account-wrap"> 
		<div class="account-right"> 
			<form action="/wireframe/index/accountinfo" method="post">
				<div class="row"><label>Email:</label> <input type="text" value="dan@email.com"></div>
				<h3>Personal Information  </h3>
				<div class="row"><label>First Name:</label> <input type="text" value="Dan"></div>
				<div class="row"><label>Last Name:</label> <input type="text" value="Testfield"></div>
				<div class="row"><label>Address 1:</label> <input type="text" value="123 Fake St"></div>
				<div class="row"><label>Address 2:</label> <input type="text" value="4th Floor"></div>
				<div class="row">
					<div class="city inline-fields"><label>City:</label> <input type="text" value="New York"></div>
					<select name="state" size="1">
						<option value="AK">AK</option>
						<option value="AL">AL</option>
						<option value="AR">AR</option>
						<option value="AZ">AZ</option>
						<option value="CA">CA</option>
						<option value="CO">CO</option>
						<option value="CT" selected>CT</option>
						<option value="DC">DC</option>
						<option value="DE">DE</option>
						<option value="FL">FL</option>
						<option value="GA">GA</option>
						<option value="HI">HI</option>
						<option value="IA">IA</option>
						<option value="ID">ID</option>
						<option value="IL">IL</option>
						<option value="IN">IN</option>
						<option value="KS">KS</option>
						<option value="KY">KY</option>
						<option value="LA">LA</option>
						<option value="MA">MA</option>
						<option value="MD">MD</option>
						<option value="ME">ME</option>
						<option value="MI">MI</option>
						<option value="MN">MN</option>
						<option value="MO">MO</option>
						<option value="MS">MS</option>
						<option value="MT">MT</option>
						<option value="NC">NC</option>
						<option value="ND">ND</option>
						<option value="NE">NE</option>
						<option value="NH">NH</option>
						<option value="NJ">NJ</option>
						<option value="NM">NM</option>
						<option value="NV">NV</option>
						<option value="NY">NY</option>
						<option value="OH">OH</option>
						<option value="OK">OK</option>
						<option value="OR">OR</option>
						<option value="PA">PA</option>
						<option value="RI">RI</option>
						<option value="SC">SC</option>
						<option value="SD">SD</option>
						<option value="TN">TN</option>
						<option value="TX">TX</option>
						<option value="UT">UT</option>
						<option value="VA">VA</option>
						<option value="VT">VT</option>
						<option value="WA">WA</option>
						<option value="WI">WI</option>
						<option value="WV">WV</option>
						<option value="WY">WY</option>
					</select>
					<div class="zip  inline-fields"><label>Zip:</label> <input type="text" value="11211"></div>
				</div>
				<h3>Contact Information </h3>
				<div class="row"><label>Telephone:</label> <input type="text" value="555-555-55555"></div>
				<div class="row"><label>Email:</label> <input type="text" value="dan@testfield.com"></div>
				<div class="order-submit">
					<input type="submit" value="Submit Changes">
				</div>
			</form>
		</div>
	</div>
</div>
