<?php $this->layout()->setLayout('account'); ?> 
<div class="int-content">
	<div class="menu-head">
		<h1>Log In</h1>
	</div>
	<div class="checkout-wrap">
		<div class="login">
			<form action="/wireframe/index/account" method="post">
				<h1>What is your email address?:</h1>
				<div class="row"><strong>My Email Address is:</strong>  </div>
				<div class="row"> <input type="text"></div>
				<div class="row checkbox-row"> Remember Me: <input type="checkbox" class="right-float"></div>
				<h1>Do you already have a password?:</h1>
				<div class="row"><a href="/wireframe/index/accountsignup">No. I am new customer.</a></div>
				<div class="row"><strong>Yes, I have a password:</strong>  </div>
				<div class="row"> <input type="password"></div>
				<div class="row"><a href="">Forgot your password?</a></div>
				<div class="row submit-row">  <input type="submit" value="Log In"></div>
			</form>
		</div>
		
  
	</div>
</div>
 