<?php $this->layout()->setLayout('account'); ?>
<div class="int-content">
	<div class="account-topnav"><a href="/wireframe/index/account">My Orders</a> | <a href="/wireframe/index/accountinfo" class="active">My Profile</a>
	</div>
	<div class="account-wrap">
		<div class="edit-save">
			<a href="/wireframe/index/accountinfo-edit">Edit Profile Information</a>
		</div>
		<div class="account-right">
			<form action="/wireframe/index/accountinfo" method="post">
				<div class="cols-account">
					<div class="col-two first">
						<div class="row"><label>Email:</label> <span class="fielddata">dan@domainname.com</span></div>
						<div class="row"><label>Password:</label> <span class="fielddata">********</span></div>
						<div class="row"><label>In what city were you born?:</label> <span class="fielddata">********</span></div>
						<h3>Personal Information </h3>
						<div class="row"><label>First Name:</label> <span class="fielddata">Dan</span></div>
						<div class="row"><label>Last Name:</label> <span class="fielddata">Testfield</span></div>
						<div class="row"><label> Phone 1:</label> <span class="fielddata">212-555-5555</span></div>
						<div class="row"><label>Phone 2 <em>(opt.)</em>:</label> <span class="fielddata">212-555-5555</span></div>
						<div class="row"><label>Birthday <em>(opt.)</em>:</label> <span class="fielddata">12/20/1974</span></div>
						<h3>Delivery Address</h3>
						<div class="row"><label>Address 1:</label>  <span class="fielddata">123 Manhattan Street</span></div>
						<div class="row"><label>Address 2:</label>   <span class="fielddata">Apartment 28</span></div>
						<div class="row">
							<div class="city inline-fields">
								<label>City:</label>   <span class="fielddata">New York</span>
								<div class="zip  inline-fields"><label>Zip:</label> <span class="fielddata">10010</span></div>
								<div class="zip  inline-fields"><label>State:</label> <span class="fielddata">New York</span></div>
							</div>
						</div>
						<h3>Billing Address  </h3>
						<div class="row"><label>Address 1:</label>  <span class="fielddata">123 Manhattan Street</span></div>
						<div class="row"><label>Address 2:</label>   <span class="fielddata">Apartment 28</span></div>
						<div class="row">
							<div class="city inline-fields">
								<label>City:</label>   <span class="fielddata">New York</span>
								<div class="zip  inline-fields"><label>Zip:</label> <span class="fielddata">10010</span></div>
								<div class="zip  inline-fields"><label>State:</label> <span class="fielddata">New York</span></div>
							</div>
						</div>
					</div>
					<div class="col-two">
						<div class="row"><label class="wide">Do you have a doorman?</label> <span class="fielddata">No</span></div>
						<div class="row"><label>Special Delivery Instructions</label></div>
						<div class="row"><span class="fieldblock">On the back porch behind the plant next to the door.</span></div>
						<div class="row checkbox-row"><span class="checked-box">x</span> I agree to the Food Allergies Disclaimer</div>
						<h3>Delivery Reminder Emails</h3>
						<div class="row checkbox-row"> 1 Day Before delivery</div>
						<div class="row"><label>Email 1:</label> <span class="fielddata">dan@domainname.com</span></div>
						<div class="row"><label>Email 2:</label> <span class="fielddata">dan@domainname.com</span></div>
						<h3>Payment Information</h3>
						<div class="row"><a href="/wireframe/index/accountpayinfo">Edit Payment Method</a></div>
						<div class="row"><label>Payment method</label> <span class="fielddata">Credit Card</span></div>
						<div class="row"><label>Card Type</label> <span class="fielddata">Visa</span></div>
						<div class="row"><label>Cardholder's Name</label> <span class="fielddata">Dan Testfield</span></div>
						<div class="row"><label>Expiration Date</label> <span class="fielddata">04/14</span></div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
