<div id="home-wrap">
	<div class="home-intro">
		<blockquote><p>A Table is an invitation.  It is how French say, "Come to the table." However, we intend it to mean much more than "dinner is ready."</p>
<p><strong>Meals that Nourish More than Your Body</strong><br />
A Table offers your family what we value most in our families, time 
at home, together. We want to help you to create your own A Table 
tradition&mdash;a meal that nourishes more than your body. 
As New Yorkers, you are encouraged to multitask, to behave as if you are 
alone, even as you sit down together with your family.  A Table provides 
an alternative. It puts the table at the center of the home and creates the 
time and space to enjoy each other's company. 
We deliver to your home well-balanced and delicious meals, good food 
intended to be eaten on real plates. Dishes prepared by a master chef 
who has collaborated with a certified nutritionist. Meals enjoyed with 
the TV off and cell phones turned to silent mode. 
</p>
<p><strong>The First Step to Reclaiming Your Home Is to Eat at Home </strong><br />
We understand your busy lives, because we live those lives, too. 
We understand what it is like to come home exhausted. We're too 
often tempted to "order in,"or to stop on the way home and pick up 
something from the market, the deli or our local Chinese. You deserve 
better. Your family deserves better. <br />
Our promise to you is to prepare and deliver a fine meal, so you can 
focus entirely on creating your own A Table experience.  With A Table 
you and your family can eat well at home two, three or more times a 
week. It's one less thing to worry about and so much more to savor. 
Our desire is to provide more than another dining alternative. We want 
to help you to experience what can only be experienced at home, in your 
home&mdash;a genuine A Table tradition. </p> 

		</blockquote>
	</div>
</div>
