<?php $this->layout()->setLayout('order'); ?>
<div id="order-steps" class="step-three">
	<ul>
		<li id="menu-step-one">Step 1. Select Dishes</li>
		<li id="menu-step-two">Step 2. Check Out</li>
		<li id="menu-step-three">Step 3. Confirm Order</li>
	</ul>
</div>
<div class="int-content">
	<div class="menu-head"> 
		<h1>Order Complete</h1>
<p>Thank you for your order!</p>
	</div>
	
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
	$(".radio").removeAttr("checked");
	$(".qty").val("1");
	$(".radio").bind("click",onOff);
	$(".add").click(add);
	$(".minus").click(minus);
	});
	function onOff() {
	if ($(this).attr("checked") == "checked") {
	$(this).parent().prepend('
	<div class="qty-wrap">
		<input type="button" value="+" class="add" />
		<input type="text" length="3" value="1" class="quantity qty" name="qty">
		<input type="button" value="-" class="minus" />
	</div>');
	$(this).parent().find(".add").bind("click",add);
	$(this).parent().find(".minus").bind("click",minus);
	$(this).remove();
	}
	}
	function add() {
	var currentVal = parseInt($(this).next(".qty").val());
	if (currentVal != NaN) {
	$(this).next(".qty").val(currentVal + 1);
	}
	}
	function minus() {
	var currentVal = parseInt($(this).prev(".qty").val());
	if (currentVal != NaN) {
	$(this).prev(".qty").val(currentVal - 1);
	}
	if ($(this).parent().find(".qty").val() <= 0) {
		$(this).parent().parent().prepend('<input type="radio" class="radio">');
		$(this).parent().parent().find(".radio").bind("click",onOff);

		$(this).parent().parent().find(".qty-wrap").remove();
	}
}
</script>