<div class="int-content">
	<h1>My Account</h1>
	<div class="account-wrap">
		<div class="account-nav">
			<ul>
				<li><a href="/wireframe/index/account">Orders</a></li>
				<li><a href="/wireframe/index/accountinfo">My Account Info</a></li>
				<li><a href="/wireframe/index/payment">Payment Information</a></li>
				<li><a href="/wireframe/index/settings">Settings</a></li>
			</ul>
		</div>
		<div class="account-right">
			<h2>Payment Information</h2>
			<form action="/wireframe/index/payment" method="post"> 
				<div class="row"><label>Credit Card:</label> <input type="text" value="XXXXXXXXXXXXXXXXX1234"></div>
				<div class="row">
					<label> </label>
					<select>
						<option>Month</option>
						<option>01</option>
						<option>02</option>
						<option>03</option>
						<option>04</option>
						<option>05</option>
						<option>06</option>
						<option selected>07</option>
						<option>08</option>
						<option>09</option>
						<option>10</option>
						<option>11</option>
						<option>12</option>
					</select>
					<select>
						<option>Year</option>
						<option>11</option>
						<option selected>12</option>
						<option>13</option>
						<option>14</option>
						<option>15</option>
					</select>
					<div class="cvv  inline-fields"><label>CVV:</label> <input type="text"></div>
				</div>
				<div class="row"><label>Name:</label> <input type="text" value="Dan Testfield"></div> 
				<div class="row"><label>Address 1:</label> <input type="text" value="123 Fake St."></div>
				<div class="row"><label>Address 2:</label> <input type="text" value="4th Floor"></div>
				<div class="row">
					<div class="city inline-fields"><label>City:</label> <input type="text"></div>
					<select name="state" size="1">
						<option value="AK">AK</option>
						<option value="AL">AL</option>
						<option value="AR">AR</option>
						<option value="AZ">AZ</option>
						<option value="CA">CA</option>
						<option value="CO">CO</option>
						<option value="CT">CT</option>
						<option value="DC">DC</option>
						<option value="DE">DE</option>
						<option value="FL">FL</option>
						<option value="GA" selected>GA</option>
						<option value="HI">HI</option>
						<option value="IA">IA</option>
						<option value="ID">ID</option>
						<option value="IL">IL</option>
						<option value="IN">IN</option>
						<option value="KS">KS</option>
						<option value="KY">KY</option>
						<option value="LA">LA</option>
						<option value="MA">MA</option>
						<option value="MD">MD</option>
						<option value="ME">ME</option>
						<option value="MI">MI</option>
						<option value="MN">MN</option>
						<option value="MO">MO</option>
						<option value="MS">MS</option>
						<option value="MT">MT</option>
						<option value="NC">NC</option>
						<option value="ND">ND</option>
						<option value="NE">NE</option>
						<option value="NH">NH</option>
						<option value="NJ">NJ</option>
						<option value="NM">NM</option>
						<option value="NV">NV</option>
						<option value="NY">NY</option>
						<option value="OH">OH</option>
						<option value="OK">OK</option>
						<option value="OR">OR</option>
						<option value="PA">PA</option>
						<option value="RI">RI</option>
						<option value="SC">SC</option>
						<option value="SD">SD</option>
						<option value="TN">TN</option>
						<option value="TX">TX</option>
						<option value="UT">UT</option>
						<option value="VA">VA</option>
						<option value="VT">VT</option>
						<option value="WA">WA</option>
						<option value="WI">WI</option>
						<option value="WV">WV</option>
						<option value="WY">WY</option>
					</select>
					<div class="zip  inline-fields"><label>Zip:</label> <input type="text" value="11211"></div>
				</div>
				<div class="order-submit">
					<input type="submit" value="Submit Changes">
				</div>
			</form>
		</div>
	</div>
</div>
