
<div class="int-content">
		<h1>My Account</h1>
	
		<div class="account-wrap">
			<div class="account-nav">
				<ul>
					<li><a href="/wireframe/index/account">Orders</a></li>
					<li><a href="/wireframe/index/accountinfo">My Account Info</a></li>
					<li><a href="/wireframe/index/payment">Payment Information</a></li>
					<li><a href="/wireframe/index/settings">Settings</a></li>
				</ul>

			</div>

			<div class="account-right">
	<h2>Payment Information</h2>
			<form action="/wireframe/index/payment" method="post">
				
				<h3>  <a href="/wireframe/index/paymentedit">Edit</a></h3>
				<div class="row"><label>Credit Card:</label> <span class="fielddata">XXXXXXXXXXXXX123</span></div>
				<div class="row">
					<label>Exp Date:</label>
					<div class="cvv  inline-fields"> <span class="fielddata">04/14</span></div>
					<div class="cvv  inline-fields"><label>CVV:</label> <span class="fielddata">123</span></div>
				</div>
				<div class="row"><label>Name:</label> <span class="fielddata">Dan Testfield</span></div>
				<div class="row"><label>Address 1:</label>  <span class="fielddata">123 Manhattan Street</span></div>
				<div class="row"><label>Address 2:</label>   <span class="fielddata">Apartment 28</span></div>
				<div class="row">
					<div class="city inline-fields">
						<label>City:</label>   <span class="fielddata">New York</span>
						<div class="zip  inline-fields"><label>State:</label> <span class="fielddata">New York</span></div>
						<div class="zip  inline-fields"><label>Zip:</label> <span class="fielddata">10010</span></div>
					</div>
				</div>
			</form>
			</div>

		</div>

</div>
