
<div class="int-content">
	<div class="menu-head">
		<div class="product-info">
		<h1>Title of Food Product</h1>
		<p><a href="" onClick="history.go(-1)">Back</a></p>
			<div class="product-row">
				<h2>Type</h2> <p>Appetizer
				</p>
			</div>
			<div class="product-row">
				<h2>Calories</h2 >
				<p>120</p>
			</div>
			<div class="product-row">
				<h2>Price</h2 >
				<p> $10</p>
			</div>
			<div class="product-row">
				<h2>Description</h2 >
				<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu ipsum ipsum. Vestibulum suscipit faucibus augue, quis volutpat lacus varius eget. Aenean mattis arcu sed ipsum suscipit porttitor. Pellentesque venenatis orci a nulla interdum ut mollis ipsum sodales.
				</p>
			</div>
			<div class="product-row">
				<h2>Nutritional Information (Ingredients)</h2 >
				<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu ipsum ipsum. Vestibulum suscipit faucibus augue, quis volutpat lacus varius eget. Aenean mattis arcu sed ipsum suscipit porttitor. Pellentesque venenatis orci a nulla interdum ut mollis ipsum sodales.
				</p>
			</div>
			<div class="product-row">
				<h2>Allergens</h2 >
				<p> May contain traces of nuts. </p>
			</div>
<p><a href="" onClick="history.go(-1)">Back</a></p>
		</div>
	</div>
</div>
</div>
