
<div class="int-content">
		<h1>My Account</h1>
	
		<div class="account-wrap">
			<div class="account-nav">
				<ul>
					<li><a href="/wireframe/index/account">Orders</a></li>
					<li><a href="/wireframe/index/accountinfo">My Account Info</a></li>
					<li><a href="/wireframe/index/payment">Payment Information</a></li>
					<li><a href="/wireframe/index/settings">Settings</a></li>
				</ul>

			</div>

			<div class="account-right">
	<h2>Settings</h2>
					<p>Coming Soon</p>				 
			</div>

		</div>

</div>
