<h2>Edit Member</h2>
<ul class="navigation">
	<li><a class="btn_back" href="/admin/members">Back</a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>

<form id="userForm" method="post" action="" enctype="multipart/form-data">
<input type="hidden" name="id" value="<?=$this->member['id']?>">
<div class="datatable">
	<table id="mediamanagertable">
		<thead>
			<tr class="header">
				<th width="250" class="first"><?=$this->member['lastname']?></th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="footer">
				<td colspan="4">&nbsp;</td>
			</tr>
		</tfoot>
		<tbody>
			<tr class="shadeoff">
				<td class="firstrow">Email:</td>
				<td>
					<?=$this->member['email']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeon">
				<td class="firstrow">Password:</td>
				<td>
					<?=$this->member['password']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeoff">
				<td class="firstrow">Security Question:</td>
				<td>
					<?=$this->member['password']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeon">
				<td class="firstrow">First Name:</td>
				<td>
					<?=$this->member['firstname']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeoff">
				<td class="firstrow">Last Name:</td>
				<td>
					<?=$this->member['lastname']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeon">
				<td class="firstrow">Phone 1:</td>
				<td>
					<?=$this->member['phone1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Phone 2(opt.):</td>
				<td>
					<?=$this->member['phone2']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Birthday(opt.):</td>
				<td>
					<?=$this->member['bday']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Address 1:</td>
				<td>
					<?=$this->member['dAddr1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Address 2:</td>
				<td>
					<?=$this->member['dAddr2']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">City:</td>
				<td>
					<?=$this->member['dCity']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Zip:</td>
				<td>
					<?=$this->member['dZip']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">State:</td>
				<td>
					<?=$this->member['dState']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Address 1:</td>
				<td>
					<?=$this->member['phone1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Address 2:</td>
				<td>
					<?=$this->member['phone2']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">City:</td>
				<td>
					<?=$this->member['phone1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Zip:</td>
				<td>
					<?=$this->member['phone2']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">State:</td>
				<td>
					<?=$this->member['phone1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Do you have a doorman?:</td>
				<td>
					<?=$this->member['doorman']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Special Delivery Instructions:</td>
				<td>
					<?=$this->member['special']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">I agree to the Food Allergies Disclaimer:</td>
				<td>
					<?=$this->member['allergies']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Delivery reminder emails:</td>
				<td>
					<?=$this->member['reminder']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Email 1:</td>
				<td>
					<?=$this->member['email1']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Email 2:</td>
				<td>
					<?=$this->member['email2']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Payment method:</td>
				<td>
                                    <select id="select" class="styled" name="data[payment]">
                                        <option id="paypal">PayPal</option>
                                        <option id="credit-card" selected>Credit Card</option>
                                    </select>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Credit card type:</td>
				<td>
                                    <select class="styled" name="data[credit]">
                                        <option>Amex</option>
                                        <option>Visa</option>
                                        <option>MasterCard</option>
                                        <option>Discovery</option>
                                    </select>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Cardholder's name:</td>
				<td>
					<?=$this->member['cardholder']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeon">
				<td class="firstrow">Credit card number:</td>
				<td>
					<?=$this->member['cardNum']?>
				</td>
				<td class="lastrow"></td>
			</tr>
                        <tr class="shadeoff">
				<td class="firstrow">Expiration date:</td>
				<td>
					<?=$this->member['expiration']?>
				</td>
				<td class="lastrow"></td>
			</tr>                        
                        
			<tr class="shadeoff">
				<td class="firstrow">Status:</td>
				<td>
					<?=$this->formSelect('data[status]', $this->member['status'], array('id'=>'status'), $this->statuses)?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr class="shadeon">
				<td class="firstrow"><input type="submit" value="Save"></td>
				<td></td>
				<td class="lastrow"></td>
			</tr>
		</tbody>
	</table>
</div>
</form>

<ul class="navigation">
	<li><a class="btn_back" href="/admin/members">Back</a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>