<h2>View Unit</h2>
<ul class="navigation">
	<li><a class="btn_back" href="/admin/units">Back</a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>

<div class="datatable">
	<table id="mediamanagertable">
		<thead>
			<tr class="header">
				<th width="125" class="first"><b><?=$this->dish['name']?></b></th>
				<th width="575"></th>
				<th class="lastrow"></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="footer">
				<td colspan="4">&nbsp;</td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td class="firstrow">Name:</td>
				<td>
					<?=$this->dish['name']?>
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr>
				<td class="firstrow">Status:</td>
				<td>
                                        <?=$this->dish['status']?>					
				</td>
				<td class="lastrow"></td>
			</tr>
			<tr>
				<td class="firstrow"><input type="submit" value="Save"></td>
				<td></td>
				<td class="lastrow"></td>
			</tr>			
		</tbody>
	</table>
</div>

<ul class="navigation">
	<li><a class="btn_back" href="/admin/units">Back</a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>

<script type="text/javascript">
$(document).ready(function() {
	$("#mediamanagertable tbody tr:even").addClass("shadeon");
	$("#mediamanagertable tbody tr:odd").addClass("shadeoff");
});
</script>