<h2>Edit Menu</h2>
<ul class="navigation">
	<li><a class="btn_back" href="/admin/menus/<?=$this->menu['type']?>"></a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>

<form id="userForm" method="post" action="" enctype="multipart/form-data">
<input type="hidden" name="id" value="<?=$this->menu['id']?>">
<div class="datatable">
    <table id="mediamanagertable">
        <thead>
            <tr class="header">
                <th width="125" class="first">Menu# <?=$this->menu['id']?></th>
                <th width="575"></th>
                <th class="lastrow"></th>
            </tr>
        </thead>
            <tfoot>
                <tr class="footer">
                    <td colspan="4">&nbsp;</td>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <td class="firstrow">Menu Name:</td>
                    <td>
                        <input type="text" name="data[name]" value="<?=$this->menu['name']?>">
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">Created By:</td>
                    <td>
                        <?=$this->menu['author']?>
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">Start Date:</td>
                    <td>
                        <input type="text" name="data[start_date]" class="date-pick" value="<?=$this->menu['start_date']?>" autocomplete="off">
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">End Date:</td>
                    <td>
                        <input type="text" name="data[end_date]" class="date-pick" value="<?=$this->menu['end_date']?>" autocomplete="off">
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">Type:</td>
                    <td>
                        
                        <input type="hidden" name="data[type]" value="<?=$this->menu['type']?>">
                        <?=$this->menu_types[$this->menu['type']]?>
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">Status:</td>
                    <td>
                        <?=$this->formSelect('data[status]', $this->menu['status'], array('id'=>'status'), $this->statuses)?>
                    </td>
                    <td class="lastrow"></td>
                </tr>
                
                <tr>
                    <td class="firstrow">Creation Date:</td>
                    <td>
                        <?=$this->menu['created']?>
                    </td>
                    <td class="lastrow"></td>
                </tr>
                <tr>
                    <td class="firstrow">Last Active:</td>
                    <td>
                        <input type="text" name="data[last_active]" class="date-pick" value="<?=$this->menu['last_active']?>" autocomplete="off">
                    </td>
                    <td class="lastrow"></td>
                </tr>
	<?php
	if ($this->menu['type'] == 'fast') 
            {
		foreach ($this->dish_categories as $cat_id => $cat_name) 
                    { ?>        
                <tr>
                        <td class="firstrow"><?=$cat_name?>:</td>
                    <td>
                        <?= $this->formSelect("items[{$cat_id}]", $this->items[$cat_id][0]['menu_item_id'], array('id'=>'cat_'.$cat_id), array(""=>"Select Item")+$this->menu_items[$cat_id])?>
                    </td>
                    <td class="lastrow"></td>
                </tr>
        <?php       }
            }       ?>
                <tr>
                    <td class="firstrow"><input type="submit" value="Save"></td>
                    <td></td>
                    <td class="lastrow"></td>
                </tr>
                
            </tbody>
	</table>
</div>
</form>

<?php
if ($this->menu['type'] == 'full') {
    $cat = ""; 
    foreach ($this->dish_categories as $cat_id =>$cat_name) {
        
        if ($cat != $cat_id) {
            
            if ($cat != '') {echo "</form></div></tbody></table>";}
            $cat = $cat_id;
        ?>
        <div class="datatable">
        <form id="userForm" method="post" action="/admin/menus/item-add" enctype="multipart/form-data">
        <input type="hidden" name="menu_id" value="<?=$this->menu['id']?>">
        <input type="hidden" name="cat_id" value="<?=$cat_id?>">
        <a name="cat_<?=$cat_id?>">&nbsp;</a>
        <h2><?=$cat_name?> Dishes</h2>
        <table id="mediamanagertable">
        <thead>
            <tr class="header">
                <th width="700"></th>
                <th class="lastrow"></th>
            </tr>
        </thead>
        <tfoot>
            <tr class="footer">
                <td colspan="4">
                    <?=$this->formSelect("item", '', array('id'=>'cat_'.$cat_id), array(""=>"Select Item")+$this->menu_items[$cat_id])?>
                    <input type="submit" value="Add">
                </td>
            </tr>
        </tfoot>
        <tbody>
        <?php }
            foreach ($this->items[$cat_id] as $item) {
                if ($item['name']) 
                    {
            ?>
                <tr>
                    <td>
                        <?=$item['name']?>
                    </td>
                    <td class="lastrow"><a href="/admin/menus/item-delete/item_id/<?=$item['menu_item_id']?>/menu_id/<?=$this->menu['id']?>/cat_id/<?=$cat_id?>" title="Delete" class="btn_delete" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
                </tr>
	<?php
                    }
		}
	}
	if ($cat != '') {
	?>
        </tbody>
	</table>
	</form>
	</div>
	<?php
	}
}
?>
</div>
<ul class="navigation">
	<li><a class="btn_back" href="/admin/menus/<?=$this->menu['type']?>"></a></li>
	<!--<li><a class="btn_export" href="">Export</a></li>-->
</ul>
<div style="clear: both;"></div>


<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    
	$("#mediamanagertable tbody tr:even").addClass("shadeon");
	$("#mediamanagertable tbody tr:odd").addClass("shadeoff");
        $(".date-pick").datepicker();
});

</script>