<?php
if ($this->dir == "DESC") $dir = "ASC"; else $dir = "DESC";
?>
<h2>Fast Menu Manager</h2>
<div style="clear: both;"></div>

<div id="search_wrapper">
	<div id="searchcopy">
		<form method="post" action="">
			<p class="row1">
				<!--<label>Search:</label><input type="text" name="mask" style="margin-right: 18px; width: 180px;" value="<?=$this->mask?>">-->
				<label>Date :</label>
				<input type="text" class="date-pick" name="mask" value="<?=$this->mask?>"><label>

				<label>Status:</label>
				<?=$this->formSelect('status', $this->status, array('id'=>'status'), array(""=>"View All")+$this->statuses)?>
			
				<input type="submit" class="submit_btn" value="Search">

				<input type="checkbox" name="csv" value="1" class="exportcheck" style="width: 15px;"><label>Export</label>
			</p>
			
		</form>
	</div>
</div>

<div style="clear: both;"></div>
<?php echo $this->paginationControl($this->list, 'Sliding', 'pagination_control.phtml'); ?>

<div id="results_wrapper">
	<div class="datatable">
		<table>
			<thead>
				<tr class="header">
					<th class="first"><a href="/admin/menus/full/sort/start_date/dir/<?=$dir?>">Menu#</a></th>
                                        <th><a href="/admin/menus/full/sort/start_date/dir/<?=$dir?>">Name</a></th>
                                        <th><a href="/admin/menus/full/sort/start_date/dir/<?=$dir?>">Created By</a></th>
                                        <th><a href="/admin/menus/full/sort/start_date/dir/<?=$dir?>">Start Date</a></th>
					<th><a href="/admin/menus/full/sort/end_date/dir/<?=$dir?>">End Date</a></th>
					<th><a href="/admin/menus/full/sort/status/dir/<?=$dir?>">Status</a></th>
                                        <th><a href="/admin/menus/full/sort/status/dir/<?=$dir?>">Creation date</a></th>
					<th>View</th>
					<th>Edit</th>
					<th class="last action">Delete</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="9"></td>
				</tr>
			</tfoot>
			<tbody>
			<?php
			$shade = true;
			foreach($this->list as $key => $val) {
				if($shade)
					$class = 'shadeoff';
				else
					$class = 'shadeon';
				$shade = !$shade;
			?>
				<tr class="<?=$class?>">
					<td class="firstrow"><?=$val['id']?></td>
                                        <td><?=$val['name']?></td>
                                        <td><?=$val['author']?></td>
                                        <td><?=$val['start_date']?></td>
					<td><?=$val['end_date']?></td>
					<td><?=$val['status']?></td>
                                        <td><?=date("Y-m-d",strtotime($val['created']))?></td>
					<td><a href="/admin/menus/view/id/<?=$val['id']?>" title="View" class="btn_view">View</a></td>
					<td><a href="/admin/menus/edit/id/<?=$val['id']?>" title="Edit" class="btn_edit">Edit</a></td>
					<td class="lastrow"><a href="/admin/menus/delete/id/<?=$val['id']?>" title="Delete" class="btn_delete" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
				</tr>
			<?php
			}
			?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	$(".date-pick").datepicker();
});
</script>