<?php
//ini_set('display_errors','1');
//error_reporting(E_ALL);
$members = "";
$headerNames = array_keys($this->members[0]);

foreach ($headerNames as $k=>$v) {
	$headers[] = '"'.str_replace("_"," ",strtoupper($v)).'"';
}
$header = implode(",",$headers)."\n";

foreach($this->members as $key => $val) {
	$memberRow = '';
	foreach ($headerNames as $k=>$v) {
		$memberRow[] .= '"'.$val[$v].'"';
	}
	$members .= implode(",",$memberRow)."\n";
}

$filename = 'admin_users'.".csv";
$out = $header.$members;

header("Content-type: text/plain");
header("Content-Disposition: attachment; filename=$filename");

echo $out;
?>