<?php
if ($this->dir == "DESC") $dir = "ASC"; else $dir = "DESC";
?>
<style>
    #results_wrapper td.cost {color: #FFFFFF;}
</style>
<h2>Order Manager</h2>
<div style="clear: both;"></div>

<div id="search_wrapper">
	<div id="searchcopy">
		<form method="post" action="">
			<p class="row1">
				<label>Search:</label><input type="text" name="mask" style="margin-right: 18px; width: 180px;" value="<?=$this->mask?>">
				<!--
				<label>Date Range:</label>
				<input type="text" class="date-pick" name="date_from"><label>to</label><input type="text" class="date-pick" name="date_to">
				-->

				<label>Status:</label>
				<?=$this->formSelect('status', $this->status, array('id'=>'status'), array(""=>"")+$this->statuses)?>
			</p>
			<div style="clear: both;"></div>
			<p class="row2">
				<input type="submit" class="submit_btn" value="Search">

				<input type="checkbox" name="csv" value="1" class="exportcheck" style="width: 15px;"><label>Export</label>
			</p>
		</form>
	</div>
</div>

<div style="clear: both;"></div>
<?php echo $this->paginationControl($this->list, 'Sliding', 'pagination_control.phtml'); ?>

<div id="results_wrapper">
	<div class="datatable">
		<table>
			<thead>
				<tr class="header">
					<th class="first"><a href="/admin/orders/index/sort/name/dir/<?=$dir?>">First Name</a></th>
					<th>Last Name</th>
                                        <th>Order Date</th>
					<td align="right" class="cost">Total Cost</td> 
                                        <th width="35"></th>
                                        <th>Status</th>  
                                        
                                        <th>View</th>
					<th>Edit</th>
					<th class="last action">Delete</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="9"></td>
				</tr>
			</tfoot>
			<tbody>
			<?php
			$shade = true;
			foreach($this->list as $key => $val) {
				if($shade)
					$class = 'shadeoff';
				else
					$class = 'shadeon';
				$shade = !$shade;
			?>
				<tr class="<?=$class?>">
					<td class="firstrow"><a class="blue" href="/admin/orders/edit/id/<?=$val['id']?>"><?=$val['firstname']?></a></td>
					<th><?=$val['lastname']?></th>
                                        <th><?=$val['orderdate']?></th>
                                        <td align="right">$ <?=$val['totalcost']?></td>
                                        <th></th>
                                        <th><?=$val['status']?></th>
					<td><a href="/admin/orders/view/id/<?=$val['id']?>" title="View" class="btn_view">View</a></td>
					<td><a href="/admin/orders/edit/id/<?=$val['id']?>" title="Edit" class="btn_edit">Edit</a></td>
					<td class="lastrow"><a href="/admin/orders/delete/id/<?=$val['id']?>" title="Delete" class="btn_delete" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
				</tr>
			<?php
			}
			?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	//$(".date-pick").datepicker();
});
</script>